// Inventory Collection
export interface Inventory {
  $id: string; // auto-generated ID from AppWrite
  user_id: string;
}

//InventoryItems Collection
export interface InventoryItem {
  $id: string; // auto-generated ID from AppWrite
  name: string;
  expiry_date: string;
  date_type: "use_by" | "best_before"; // Enum for date type
  is_frozen: boolean;
  is_removed: boolean;
  reason_for_removal?: "expired" | "consumed" | "preference" | "other";
  inventory_id: string;
}

export interface FlaggedItem {
  $id: string; // auto-generated ID from AppWrite
  name: string;
  expiry_date: string;
  date_type: "use_by" | "best_before"; // Enum for date type
  inventory_id: string;
}

// ShoppingList Collection
export interface ShoppingList {
  $id: string; //auo generated by Appwrite
  user_id: string;
}
// ShoppingListItem Collection
export interface ListItem {
  $id: string; //auto generated by Appwrite
  name: string;
  quantity: number;
  is_purchased: boolean;
  shopping_list_id: string;
}

// Insights Collection
export interface Insight {
  $id: string; // auto-generated ID from AppWrite
  user_id: string;
  items_consumed: number;
  items_expired: number;
  items_discarded_preference: number;
  items_logged: number;
}
